name: "build"
on: [push]
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build Docker image"
        run: | 
          docker build . -f containers/Dockerfile \
            - --build-arg=containers/env.base.yml \
            -t ghcr.io/${{ github.repository }}:v0.0.0 \
            -t ghcr.io/${{ github.repository }}:latest  
      - name: "Release Docker image"
        run: | 
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.repository_owner }} --password-stdin
          docker push ghcr.io/${{ github.repository }}:v0.0.0
          docker push ghcr.io/${{ github.repository }}:latest
          